[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
textfeed = "Fov2FcuzX37TPe8fRq94UcWgaBW37NEpp4FK2MRY3hri"

[programs.localnet]
textfeed = "Fov2FcuzX37TPe8fRq94UcWgaBW37NEpp4FK2MRY3hri"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/my_new_wallet.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
